# Generated by Django 5.0.14 on 2026-09-01 01:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('etiqueta_mas_18', models.BooleanField(default=False)),
                ('archivo_exe', models.FileField(blank=True, null=True, upload_to='juegos_exe/')),
                ('estado', models.CharField(choices=[('cuarentena', 'En Cuarentena (Análisis Anti-Malware)'), ('publicado', 'Publicado (Archivo Limpio)'), ('baneado', 'Baneado (Contenido Rechazado)')], default='cuarentena', max_length=20)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlertaMalware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_alerta', models.DateTimeField(auto_now_add=True)),
                ('detalles_analisis', models.TextField(help_text='Detalles del escáner (ej. VirusTotal)')),
                ('resuelta', models.BooleanField(default=False)),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.juego')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('jugador', 'Jugador / Usuario'), ('desarrollador', 'Desarrollador Indie')], default='jugador', max_length=20)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('baneado', models.BooleanField(default=False)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LicenciaCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.juego')),
                ('jugador', models.ForeignKey(limit_choices_to={'rol': 'jugador'}, on_delete=django.db.models.deletion.CASCADE, to='administrador.perfilusuario')),
            ],
        ),
        migrations.AddField(
            model_name='juego',
            name='desarrollador',
            field=models.ForeignKey(limit_choices_to={'rol': 'desarrollador'}, on_delete=django.db.models.deletion.CASCADE, to='administrador.perfilusuario'),
        ),
    ]
